## Introduction

### Problem statement

Given the olympics dataset from 1896 to 2016 olympics. The dataset is made up combining the two datasets which are the athlete events dataset and region datasets referred to as df and df1 respectively. The dataset contains different kind of data including but not limited to name of the athletes, sport they play, city hosting the games, which year it was and etc. We are required to visualize the data to the best of our abilities.

### Attributes

#### ID - A unique number used to identify an athlete
#### Name - Full name of an athlete
#### Sex - Gender (M/F)
#### Age - How old the athlete is in years
#### Height - How tall or short the athlete is in cm
#### Weight - How heavy the athlete is in kilograms
#### Team - Country of the athlete
#### NOC - National olympic committee the athlete represent
#### Games - Year and season on which the olypics were held
#### Season - The season the olympics were held
#### Year - The year the olympics were held
#### City - The city in which the olympics were held
#### Sport - Type of games they are competing in
#### Event - Description of the sport (e.g. Judo Men's Extra-Lightweight)
#### Medal - Type of medal won

### Acknowledgement

[Kaggle](https://www.kaggle.com/heesoo37/olympic-history-data-a-thorough-analysis)

## Data cleaning

### Modules Import

In [1]:
# Modules
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

### Missing data

In [2]:
# Defining dataset

df = pd.read_csv('athlete_events.csv')
df1 = pd.read_csv('noc_regions.csv')

### Data overview

In [3]:
df.head()

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer     London           Judo   
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN

In [4]:
df1.head()

NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

### Dealing with null values

In [5]:
df.isnull().sum()

ID             0
Name           0
Sex            0
Age         9474
Height     60171
Weight     62875
Team           0
NOC            0
Games          0
Year           0
Season         0
City           0
Sport          0
Event          0
Medal     231333
dtype: int64

In [6]:
df1.isnull().sum()

NOC         0
region      3
notes     209
dtype: int64

We can see that we have null values in both datasets, now we investigate the null values and see how we can deal with them

In [7]:
df1[df1['region'].isnull() == True]

NOC region                 notes
168  ROT    NaN  Refugee Olympic Team
208  TUV    NaN                Tuvalu
213  UNK    NaN               Unknown

In [8]:
df1['region'].unique()

array(['Afghanistan', 'Curacao', 'Albania', 'Algeria', 'Andorra',
       'Angola', 'Antigua', 'Australia', 'Argentina', 'Armenia', 'Aruba',
       'American Samoa', 'Austria', 'Azerbaijan', 'Bahamas', 'Bangladesh',
       'Barbados', 'Burundi', 'Belgium', 'Benin', 'Bermuda', 'Bhutan',
       'Bosnia and Herzegovina', 'Belize', 'Belarus', 'Czech Republic',
       'Boliva', 'Botswana', 'Brazil', 'Bahrain', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Central African Republic', 'Cambodia', 'Canada',
       'Cayman Islands', 'Republic of Congo', 'Chad', 'Chile', 'China',
       'Ivory Coast', 'Cameroon', 'Democratic Republic of the Congo',
       'Cook Islands', 'Colombia', 'Comoros', 'Cape Verde', 'Costa Rica',
       'Croatia', 'Greece', 'Cuba', 'Cyprus', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'Eritrea',
       'El Salvador', 'Spain', 'Estonia', 'Ethiopia', 'Russia', 'Fiji',
       'Finland', 'France', 'Germany', 'Micronesia', 'Gabon', 'Gambi

We can see that the region column from df1 is made up of countries from around the world. For countries with region as null we can see that the corresponding notes values has the equivalent of countries so we can substitute the region null values with the notes values.

In [9]:
#Subtituting region null values with their correponding notes values
for i in df1[df1['region'].isnull()==True].index:
    df1['region'].iloc[i] = df1['notes'].iloc[i]

In [10]:
df1.isnull().sum()

NOC         0
region      0
notes     209
dtype: int64

Since we can see that most of the values in the notes values are null and we are not in need of the column for our visuals we can drop it

In [11]:
# Dropping the notes column
df1.drop('notes', axis = 1,inplace = True)

In [12]:
df1

NOC       region
0    AFG  Afghanistan
1    AHO      Curacao
2    ALB      Albania
3    ALG      Algeria
4    AND      Andorra
..   ...          ...
225  YEM        Yemen
226  YMD        Yemen
227  YUG       Serbia
228  ZAM       Zambia
229  ZIM     Zimbabwe

[230 rows x 2 columns]

In [13]:
df['Weight'].unique()

array([ 80.        ,  60.        ,          nan,  82.        ,
        75.        ,  72.        ,  96.        ,  76.5       ,
        70.        ,  55.5       ,  65.        ,  85.        ,
        64.        , 130.        , 125.        ,  89.        ,
        77.        ,  76.        ,  98.        ,  78.        ,
        73.        ,  93.        ,  74.        , 106.        ,
        58.        ,  66.        ,  71.        ,  90.        ,
        87.        ,  49.        ,  48.        ,  83.        ,
        86.        ,  55.        ,  67.        ,  97.        ,
       105.        ,  43.        ,  79.        ,  51.        ,
        88.        ,  62.        ,  53.        , 104.        ,
        57.        ,  63.        ,  52.        ,  91.        ,
        94.        ,  56.        ,  68.        ,  61.        ,
        69.        ,  46.        , 100.        ,  81.        ,
        92.        , 120.        ,  95.        ,  59.        ,
        50.        , 117.5       ,  54.        ,  47.  

In [14]:
df['Height'].unique()

array([180., 170.,  nan, 185., 188., 183., 168., 186., 182., 172., 159.,
       171., 184., 175., 189., 176., 163., 187., 169., 174., 190., 194.,
       177., 167., 164., 198., 165., 156., 179., 178., 166., 181., 155.,
       160., 173., 192., 195., 191., 203., 158., 154., 153., 152., 193.,
       162., 197., 157., 207., 147., 150., 202., 161., 210., 205., 200.,
       148., 208., 140., 213., 204., 151., 196., 146., 201., 132., 149.,
       199., 211., 215., 139., 206., 135., 142., 217., 209., 145., 221.,
       144., 214., 143., 218., 127., 223., 216., 141., 212., 131., 136.,
       137., 138., 220., 130., 219., 133., 128., 226.])

In [15]:
df['Age'].unique()

array([24., 23., 34., 21., 25., 27., 31., 33., 18., 26., 22., 30., 32.,
       28., 54., 20., 17., 43., 47., 29., 41., 45., 49., 53., 57., nan,
       19., 38., 35., 16., 37., 15., 42., 46., 40., 36., 14., 39., 48.,
       52., 44., 55., 50., 71., 63., 51., 58., 13., 60., 75., 65., 56.,
       64., 68., 84., 12., 72., 59., 61., 70., 74., 62., 67., 69., 73.,
       66., 11., 76., 88., 96., 80., 10., 81., 77., 97.])

In [16]:
df['Medal'].unique()

array([nan, 'Gold', 'Bronze', 'Silver'], dtype=object)

From the unique values above we can see that weight values are decimals, age and height values are integers and the medal vales are characters. So we can fill the null values for weight with the mean while the age and height values are filled with the their respective mode values. As for the medal values we can fill the null values with none since if your value is null it means you did not win anything for that competition.

In [17]:
# filling the null values for df
for i in ['Weight','Height','Age']:
    if i == 'Weight':
        df[i].fillna(np.mean(df[i]),inplace=True)
    else:
        df[i].fillna(float(df[i].mode()),inplace=True)
df['Medal'].fillna('None',inplace=True)

In [18]:
df.isna().sum()

ID        0
Name      0
Sex       0
Age       0
Height    0
Weight    0
Team      0
NOC       0
Games     0
Year      0
Season    0
City      0
Sport     0
Event     0
Medal     0
dtype: int64

In [19]:
# Making the two dataset one big data set
Data = pd.merge(df,df1,on = 'NOC')

In [20]:
Data

ID                Name Sex   Age  Height     Weight     Team  NOC  \
0            1           A Dijiang   M  24.0   180.0  80.000000    China  CHN   
1            2            A Lamusi   M  23.0   170.0  60.000000    China  CHN   
2          602       Abudoureheman   M  22.0   182.0  75.000000    China  CHN   
3         1463           Ai Linuer   M  25.0   160.0  62.000000    China  CHN   
4         1464           Ai Yanhan   F  14.0   168.0  54.000000    China  CHN   
...        ...                 ...  ..   ...     ...        ...      ...  ...   
270762  120575     Mamorallo Tjoka   F  23.0   150.0  56.000000  Lesotho  LES   
270763  120575     Mamorallo Tjoka   F  27.0   150.0  56.000000  Lesotho  LES   
270764  122166  M'apotlaki Ts'elho   F  15.0   180.0  70.702393  Lesotho  LES   
270765  122215          Lefa Tsapi   M  23.0   170.0  63.000000  Lesotho  LES   
270766  122299       Mosolesa Tsie   M  20.0   175.0  75.000000  Lesotho  LES   

              Games  Year  Season            City       Sport  \
0       1992 Summer  1992  Summer       Barcelona  Basketball   
1       2012 Summer  2012  Summer          London        Judo   
2       2000 Summer  2000  Summer          Sydney      Boxing   
3       2004 Summer  2004  Summer          Athina   Wrestling   
4       2016 Summer  2016  Summer  Rio de Janeiro    Swimming   
...             ...   ...     ...             ...         ...   
270762  2008 Summer  2008  Summer         Beijing   Athletics   
270763  2012 Summer  2012  Summer          London   Athletics   
270764  1996 Summer  1996  Summer         Atlanta   Athletics   
270765  1984 Summer  1984  Summer     Los Angeles      Boxing   
270766  2000 Summer  2000  Summer          Sydney      Boxing   

                                           Event Medal   region  
0                    Basketball Men's Basketball  None    China  
1                   Judo Men's Extra-Lightweight  None    China  
2                      Boxing Men's Middleweight  None    China  
3       Wrestling Men's Lightweight, Greco-Roman  None    China  
4          Swimming Women's 200 metres Freestyle  None    China  
...                                          ...   ...      ...  
270762                Athletics Women's Marathon  None  Lesotho  
270763                Athletics Women's Marathon  None  Lesotho  
270764    Athletics Women's 4 x 100 metres Relay  None  Lesotho  
270765                 Boxing Men's Welterweight  None  Lesotho  
270766                 Boxing Men's Welterweight  None  Lesotho  

[270767 rows x 16 columns]

In [21]:
Data.isna().sum()

ID        0
Name      0
Sex       0
Age       0
Height    0
Weight    0
Team      0
NOC       0
Games     0
Year      0
Season    0
City      0
Sport     0
Event     0
Medal     0
region    0
dtype: int64

We have decided to use Google Data Studio to produce a dashboard using this data

In [22]:
Data.to_csv('Olympics.csv',index=False)

In [40]:
Data[Data['Year']>1970]['region'].nunique()

207

In [37]:
Data[Data['Year']>1935]['Sport'].nunique()

55

In [38]:
Data[Data['Year']>1935]['ID'].nunique()

119479

In [33]:
Data[(Data['Year']>1927) & (Data['Medal']!='None')]['Medal'].count()

34041

In [39]:
Data[Data['Year']>1935]['Event'].nunique()

531

In [34]:
print(Data[Data['Year']>1927]['region'].nunique(),Data[Data['Year']>1927]['Sport'].nunique(),Data[Data['Year']>1927]['ID'].nunique(),Data[(Data['Year']>1927) & (Data['Medal']!='None')]['Medal'].count(),Data[Data['Year']>1927]['Event'].nunique())

207 55 124230 34041 539
